language: python
sudo: False
cache: pip
addons:
    artifacts:
        s3_region: us-west-1
        paths:
            - $(ls dist/*.whl | tr "\n" ':')

matrix:
    include:
        - python: 2.7
        - python: 3.3
        - python: 3.4
        - python: 3.5
        - python: 3.6
        - python: pypy
          env: PY_VERSION=pypy2-5.6
        - python: pypy
          env: PY_VERSION=pypy2-5.4
        - python: pypy
          env: PY_VERSION=pypy2-5.3

install:
    - |
        if [ -n "$PY_VERSION" ]; then
            git clone --depth 1 https://github.com/pyenv/pyenv ~/.pyenv
            PYENV_ROOT="$HOME/.pyenv"
            PATH="$PYENV_ROOT/bin:$PATH"
            eval "$(pyenv init -)"
            # Install the latest version of pypy matching the spec
            latest_py_version=$(pyenv install -l | grep -E "$PY_VERSION" | tail -1)
            echo "Using Python $latest_py_version"
            pyenv install $latest_py_version
            pyenv global $latest_py_version
        fi
    - ./configure

script:
    - |
        # activate the PyPy env we installed via our custom pyenv in the install stage
        if [ -n "$PY_VERSION" ]; then
            PYENV_ROOT="$HOME/.pyenv"
            PATH="$PYENV_ROOT/bin:$PATH"
            eval "$(pyenv init -)"
        fi
    - ./test
    - python setup.py bdist_wheel

env:
    global:
        - NO_VIRTUALENV=1
        - ARTIFACTS_KEY=AKIAJPQGWFL6SYXPMUBA
        - ARTIFACTS_BUCKET=porridge-artifacts
        # ARTIFACTS_SECRET:
        - secure: "MZsh1ZveQqGIVCof+l53k6uviay+J45Mo7hEX5XI3r41oBQIgSm/P2D2/JNfAaN20rd2V9DmEhHn+SLfJZMTIvza8wA8d60dkPCxzFGgY5UULLt0GfPlTWTzlRox03CcHi2Bb8HGieBXz3vNEfNQhX//YWqw6y+G1Awz1TFso6uu8nHu4P1SoPZZkIby8fvr47dWaC8hSqzOVkqI+7Ss/hhPywS50n3vpmW0VlHRA8N0RRow6toecdb6jg8dOY2B4UgIVVzQx0i3R5y1tHic7C1ztAHESVO+QiYmF3oW5mr4LHF0eLMXKkEoDHNzYeQMh7oUnpprQQDfBan6vEbCLjw55lFj21A7ev//faGEN6qPxSoaWE5M37y81usorT8LVsGdbSAjYAvNjqtRSV9vUzpn9RvbYnzCk2OWmMqDEfs6rzQbvqLkZO7EjC6bq+u9SLYDpBHlqCw+42E/Ls1/7JVoGcTQm4I1iozJ2BLzcFggPN362u8HaWPq9CKb8lMKsku4tOvzlXhNQ9XjExoEVtglvI14mtNhhE6MNufXnR1IdyM8KSzL2a/6f9vX0PdXlhQo77ozEqbwdZLzkS9XNVK05CnQY/y8OCc0uDq1OzOHp/0nUbO+yngTm+WV7TnV9udt/Lg8QGLBdYchw80zZrpVXQTrahcpLXEQ1xnP2C4="
